// src/app/(frontend)/pricing/[slug]/page.tsx
import React from 'react'
import { notFound } from 'next/navigation'
import { getPricingBySlug, getPricing } from '@/lib/getPageData'
import Image from 'next/image'
import Link from 'next/link'

// Generate static params for all pricing items
export async function generateStaticParams() {
  const pricing = await getPricing()
  return pricing.map((item) => ({
    slug: item.slug,
  }))
}

// Generate metadata for SEO
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const item = await getPricingBySlug(slug)

  if (!item) {
    return {
      title: 'Package Not Found',
    }
  }

  return {
    title: `${item.metadata.title} - CarPit Garage Árak`,
    description: item.metadata.description,
  }
}

export default async function PricingPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const item = await getPricingBySlug(slug)

  if (!item) {
    notFound()
  }

  const { metadata } = item

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="relative h-[40vh] min-h-[300px] bg-linear-to-t from-background to-background/80">
        {metadata.image && (
          <Image
            src={metadata.image}
            alt={metadata.title}
            fill
            className="object-cover opacity-20"
            priority
          />
        )}
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="text-center px-4">
            {metadata.popular && (
              <span className="inline-block bg-accent text-white px-4 py-1 rounded-full text-sm font-semibold mb-4">
                Népszerű választás
              </span>
            )}
            <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">{metadata.title}</h1>
            <p className="text-xl text-white/70">{metadata.category}</p>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-16">
        {/* Price and Duration */}
        <div className="bg-white/5 rounded-lg p-8 mb-12 text-center">
          <p className="text-5xl font-bold text-accent mb-2">{metadata.price}</p>
          {metadata.duration && <p className="text-white/60">Időtartam: {metadata.duration}</p>}
        </div>

        {/* Description */}
        <div className="mb-12">
          <h2 className="text-2xl font-bold text-white mb-4">Leírás</h2>
          <p className="text-white/80 text-lg leading-relaxed">{metadata.description}</p>
        </div>

        {/* Features */}
        {metadata.features && metadata.features.length > 0 && (
          <div className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-6">Mit tartalmaz a csomag?</h2>
            <ul className="space-y-3">
              {metadata.features.map((feature, index) => (
                <li key={index} className="flex items-start">
                  <svg
                    className="w-6 h-6 text-accent mr-3 mt-0.5 shrink-0"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M5 13l4 4L19 7"
                    />
                  </svg>
                  <span className="text-white/80">{feature}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Services included */}
        {metadata.services && metadata.services.length > 0 && (
          <div className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-6">Szolgáltatások</h2>
            <div className="grid md:grid-cols-2 gap-3">
              {metadata.services.map((service, index) => (
                <div key={index} className="flex items-start bg-white/5 rounded-lg p-4">
                  <svg
                    className="w-5 h-5 text-accent mr-3 mt-0.5 shrink-0"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M5 13l4 4L19 7"
                    />
                  </svg>
                  <span className="text-white/80 text-sm">{service}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Vehicle Types */}
        {metadata.vehicleTypes && metadata.vehicleTypes.length > 0 && (
          <div className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-4">Alkalmas járművek</h2>
            <div className="flex flex-wrap gap-2">
              {metadata.vehicleTypes.map((type, index) => (
                <span key={index} className="bg-white/10 text-white px-4 py-2 rounded-full text-sm">
                  {type}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Notes */}
        {metadata.notes && (
          <div className="mb-12">
            <div className="bg-accent/10 border border-accent/20 rounded-lg p-6">
              <h3 className="text-white font-semibold mb-2 flex items-center">
                <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                  />
                </svg>
                Fontos információ
              </h3>
              <p className="text-white/80 text-sm">{metadata.notes}</p>
            </div>
          </div>
        )}

        {/* CTA */}
        <div className="border-t border-white/10 pt-12">
          <div className="bg-white/5 rounded-lg p-8 text-center">
            <h3 className="text-2xl font-bold text-white mb-4">Foglald le időpontodat még ma!</h3>
            <p className="text-white/70 mb-6">
              Hívj minket vagy írj üzenetet, és egyeztessük a részleteket
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a
                href="tel:+36703339809"
                className="inline-block bg-accent text-white px-8 py-3 rounded-lg font-semibold hover:bg-accent/90 transition-colors"
              >
                +36 70 333 9809
              </a>
              <Link
                href="/#contact"
                className="inline-block border border-white/20 text-white px-8 py-3 rounded-lg font-semibold hover:bg-white/5 transition-colors"
              >
                Üzenet küldése
              </Link>
            </div>
          </div>
        </div>

        {/* Back link */}
        <div className="mt-12 text-center">
          <Link
            href="/#pricing"
            className="text-accent hover:text-accent/80 transition-colors inline-flex items-center gap-2"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M15 19l-7-7 7-7"
              />
            </svg>
            Vissza az árakhoz
          </Link>
        </div>
      </div>
    </div>
  )
}

// src/design-example/src/routes/pricing/[slug]/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import SmoothScrollWrapper from '$lib/components/SmoothScrollWrapper.svelte';

  export let data;

  $: pricingItem = data.item;
  $: otherItems = data.otherItems;
  let isClient = false;

  onMount(() => {
    isClient = true;
  });
</script>

<svelte:head>
  <title>{pricingItem.metadata.title} | Carpit Garage Árak</title>
  <meta name="description" content={pricingItem.metadata.description} />
</svelte:head>

<SmoothScrollWrapper>
  {#snippet children()}
    <!-- Pricing Detail Header -->
<section class="py-24 md:py-32 bg-gradient-to-b from-background to-card">
  <div class="max-w-7xl mx-auto px-6 md:px-12">
    <div class="text-center mb-16">
      <div class="flex items-center justify-center gap-3 mb-6">
        <span class="w-2 h-2 bg-accent rounded-full"></span>
        <span class="text-accent/80 font-medium tracking-wider text-sm uppercase">Ár részletei</span>
        <span class="w-2 h-2 bg-accent rounded-full"></span>
      </div>
      
      <h1 class="font-display text-4xl md:text-6xl font-bold text-white mb-6">{pricingItem.metadata.title}</h1>
      
      <div class="flex justify-center gap-4 mb-8">
        <span class="bg-accent/10 px-4 py-2 border border-accent/20 backdrop-blur-sm inline-block">
          <span class="text-accent font-semibold">{pricingItem.metadata.price}</span>
        </span>
        <span class="bg-card px-4 py-2 border border-white/20 inline-block">
          <span class="text-white/80">{pricingItem.metadata.duration}</span>
        </span>
        <span class="bg-card px-4 py-2 border border-white/20 inline-block">
          <span class="text-white/80">{pricingItem.metadata.category}</span>
        </span>
      </div>
      
      <p class="text-lg text-white/70 font-light leading-relaxed max-w-3xl mx-auto mb-8">
        {pricingItem.metadata.description}
      </p>
    </div>
  </div>
</section>

<!-- Pricing Content Section -->
<section class="py-16 md:py-24 bg-card">
  <div class="max-w-6xl mx-auto px-6 md:px-12">
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">
      <div class="prose prose-invert max-w-none">
        <h2 class="font-display text-2xl font-bold text-white mb-6">Szolgáltatás részletei</h2>
        <p class="text-white/80 leading-relaxed text-lg mb-8">
          {pricingItem.content}
        </p>
        
        <h3 class="font-display text-xl font-bold text-white mb-4 mt-8">A csomag tartalmazza</h3>
        <ul class="list-disc list-inside text-white/80 space-y-2">
          {#each pricingItem.metadata.features || [] as feature}
            <li>{feature}</li>
          {/each}
        </ul>
      </div>
      
      <div>
        <img src={pricingItem.metadata.image} alt={pricingItem.metadata.title} class="w-full h-96 object-cover rounded-lg border border-white/20 shadow-2xl" />
      </div>
    </div>
  </div>
</section>

<!-- CTA Section -->
<section class="py-16 md:py-24 bg-gradient-to-r from-card/30 to-card/10 border-t border-b border-white/10">
  <div class="max-w-7xl mx-auto px-6 md:px-12">
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
      <div>
        <h2 class="font-display text-3xl md:text-4xl font-bold text-white mb-6">
          Foglaljon időpontot ezen a csomagon
        </h2>
        <p class="text-white/70 font-light leading-relaxed mb-8">
          Válassza ezt a csomagot és élvezze autójának újjászületését.
        </p>
      </div>
      <div class="lg:text-right">
        <a
          href="tel:+36703339809"
          class="inline-flex items-center gap-3 px-8 py-4 bg-accent text-white font-semibold tracking-wide hover:bg-accent/90 transition-colors duration-300"
        >
          <span>Időpont foglalás</span>
          <span class="text-xl">→</span>
        </a>
      </div>
    </div>
  </div>
</section>

<!-- Other Pricing Items Section -->
<section class="py-16 md:py-24 bg-background">
  <div class="max-w-7xl mx-auto px-6 md:px-12">
    <div class="text-center mb-12">
      <h2 class="font-display text-3xl md:text-4xl font-bold text-white mb-4">
        Más csomagok
      </h2>
      <p class="text-white/70 font-light">
        Tekintse meg teljes árlistánkat
      </p>
    </div>
    
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {#each otherItems as item}
        <a href="/pricing/{item.slug}" class="block group" data-sveltekit-preload-data="hover">
          <div class="bg-card border border-white/20 hover:border-accent/50 transition-all duration-300 p-6 h-full flex flex-col">
            <div class="flex-1">
              <h3 class="font-display text-xl font-bold text-white mb-3 group-hover:text-accent transition-colors">
                {item.metadata.title}
              </h3>
              <p class="text-white/70 font-light text-sm mb-4">
                {item.metadata.description}
              </p>
            </div>
            <div class="mt-4">
              <div class="flex justify-between items-end">
                <span class="bg-accent/10 px-3 py-1 text-accent text-sm font-medium">
                  {item.metadata.price}
                </span>
                <span class="text-white/60 text-xs">
                  {item.metadata.duration}
                </span>
              </div>
            </div>
          </div>
        </a>
      {/each}
    </div>
  </div>
</section>
  {/snippet}
</SmoothScrollWrapper>
