// src/app/(frontend)/aszf/page.tsx
import React from 'react'
import Link from 'next/link'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Általános Szerződési Feltételek - CarPit Garage',
  description: 'A CarPit Garage autókozmetika szolgáltatásainak általános szerződési feltételei',
}

export default function ASZFPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="relative bg-[#0D0D0D] border-b border-white/10">
        <div className="max-w-4xl mx-auto px-4 py-16">
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">
            Általános Szerződési Feltételek
          </h1>
          <p className="text-xl text-white/70">CarPit Garage</p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-16">
        <div className="prose prose-invert prose-orange max-w-none">
          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-4">1. Általános rendelkezések</h2>
            <p className="text-white/80 mb-4">
              A jelen Általános Szerződési Feltételek (továbbiakban: ÁSZF) tartalmazzák a CarPit
              Garage (továbbiakban: Szolgáltató) által nyújtott autókozmetikai és detailing
              szolgáltatások igénybevételének feltételeit.
            </p>
            <p className="text-white/80 mb-4">
              A szolgáltatások megrendelésével az Ügyfél elfogadja a jelen ÁSZF-ben foglalt
              feltételeket.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-4">2. A Szolgáltató adatai</h2>
            <ul className="text-white/80 space-y-2">
              <li>Név: CarPit Garage</li>
              <li>Telefonszám: +36 70 333 9809</li>
              <li>E-mail: info@carpitgarage.hu</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-4">3. Szolgáltatások</h2>
            <p className="text-white/80 mb-4">A Szolgáltató az alábbi szolgáltatásokat nyújtja:</p>
            <ul className="text-white/80 space-y-2 list-disc list-inside">
              <li>Autómosás (külső és belső)</li>
              <li>Polírozás</li>
              <li>Kerámia bevonat</li>
              <li>Kárpittisztítás</li>
              <li>Nano bevonat</li>
              <li>Egyéb detailing szolgáltatások</li>
            </ul>
            <p className="text-white/80 mt-4">
              A szolgáltatások részletes leírása és árazása a weboldalon található.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-4">4. Időpontfoglalás</h2>
            <p className="text-white/80 mb-4">
              Az időpontfoglalás telefonon vagy e-mailben történik. A Szolgáltató az időpont
              visszaigazolásával kötelezettséget vállal a szolgáltatás elvégzésére.
            </p>
            <p className="text-white/80 mb-4">
              Az Ügyfél köteles az egyeztetett időpontban megjelenni, vagy legalább 24 órával
              korábban lemondani az időpontot.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-4">5. Árak és fizetés</h2>
            <p className="text-white/80 mb-4">
              A szolgáltatások árai a weboldalon feltüntetett árak szerint alakulnak. Az árak
              tartalmazzák az anyagköltséget és a munkadíjat.
            </p>
            <p className="text-white/80 mb-4">
              A fizetés készpénzben vagy bankkártyával történik a szolgáltatás elvégzése után.
            </p>
            <p className="text-white/80 mb-4">
              A Szolgáltató fenntartja a jogot az árak módosítására. Az árak módosítása a már
              lefoglalt időpontokra nem vonatkozik.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-4">6. Felelősség</h2>
            <p className="text-white/80 mb-4">
              A Szolgáltató gondosan végzi munkáját és a szakmai szabályok betartásával dolgozik.
            </p>
            <p className="text-white/80 mb-4">
              A Szolgáltató nem vállal felelősséget a jármű meglévő károsodásaiért, gyári hibákért
              vagy az Ügyfél által nem jelentett problémákért.
            </p>
            <p className="text-white/80 mb-4">
              Az Ügyfél köteles a járműben lévő értékeket elvinni vagy biztonságos helyen tárolni. A
              Szolgáltató nem vállal felelősséget a járműben hagyott tárgyakért.
            </p>
          </section>
          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-4">8. Adatvédelem</h2>
            <p className="text-white/80 mb-4">
              A Szolgáltató az Ügyfél személyes adatait az{' '}
              <Link href="/adatvedelem" className="text-accent hover:text-accent/80 underline">
                Adatvédelmi Tájékoztatóban
              </Link>{' '}
              foglaltak szerint kezeli.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-4">9. Egyéb rendelkezések</h2>
            <p className="text-white/80 mb-4">
              A jelen ÁSZF-ben nem szabályozott kérdésekben a magyar jog, különösen a Polgári
              Törvénykönyv rendelkezései az irányadók.
            </p>
            <p className="text-white/80 mb-4">
              A Szolgáltató fenntartja a jogot a jelen ÁSZF módosítására. A módosítások a weboldalon
              történő közzététellel lépnek hatályba.
            </p>
          </section>

          <section className="mb-12">
            <p className="text-white/60 text-sm">Utolsó frissítés: 2026. január 1.</p>
          </section>
        </div>

        {/* Back link */}
        <div className="mt-12 pt-8 border-t border-white/10">
          <Link
            href="/"
            className="text-accent hover:text-accent/80 transition-colors inline-flex items-center gap-2"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M15 19l-7-7 7-7"
              />
            </svg>
            Vissza a főoldalra
          </Link>
        </div>
      </div>
    </div>
  )
}

// src/design-example/src/routes/aszf/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import SmoothScrollWrapper from '$lib/components/SmoothScrollWrapper.svelte';
</script>

<svelte:head>
	<title>Általános Szerződési Feltételek - CarPit Garage</title>
	<meta name="description" content="CarPit Garage általános szerződési feltételei és szolgáltatási feltételei.">
</svelte:head>

<SmoothScrollWrapper>
	{#snippet children()}
		<main class="min-h-screen bg-[#0D0D0D] text-white">
	<div class="max-w-4xl mx-auto px-4 py-16">
		<div class="mb-8">
			<a href="/" class="text-accent hover:text-accent/80 transition-colors duration-300">
				← Vissza a főoldalra
			</a>
		</div>

		<h1 class="text-4xl font-bold mb-8 text-accent">Általános Szerződési Feltételek</h1>

		<div class="prose prose-invert max-w-none">
			<section class="mb-8">
				<h2 class="text-2xl font-semibold mb-4 text-white">1. Általános rendelkezések</h2>
				<p class="text-white/80 leading-relaxed mb-4">
					Jelen Általános Szerződési Feltételek (továbbiakban: ÁSZF) a CarPit Garage által nyújtott
					autókozmetikai és detailing szolgáltatásokra vonatkoznak.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-semibold mb-4 text-white">2. Szolgáltató adatai</h2>
				<div class="text-white/80 leading-relaxed mb-4">
					<p><strong>Név:</strong> CarPit Garage</p>
					<p><strong>Cím:</strong> 1172 Budapest, Cinkotai út 26.</p>
					<p><strong>Email:</strong> info@carpitgarage.hu</p>
					<p><strong>Telefon:</strong> +36 70 333 9809</p>
				</div>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-semibold mb-4 text-white">3. Szolgáltatások</h2>
				<p class="text-white/80 leading-relaxed mb-4">
					Szolgáltatásaink körébe tartoznak:
				</p>
				<ul class="list-disc list-inside text-white/80 space-y-2 mb-4">
					<li>Autó külső és belső tisztítás</li>
					<li>Polírozás</li>
					<li>Kerámia bevonat alkalmazás</li>
					<li>Kárpittisztítás</li>
					<li>Egyéb autókozmetikai szolgáltatások</li>
				</ul>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-semibold mb-4 text-white">4. Árak és fizetés</h2>
				<p class="text-white/80 leading-relaxed mb-4">
					Az árak a szolgáltatás megkezdésekor érvényes árjegyzék szerint alakulnak.
					Az árak forintban értendők és tartalmazzák az ÁFÁ-t.
				</p>
				<p class="text-white/80 leading-relaxed mb-4">
					Fizetés készpénzzel vagy bankkártyával lehetséges a szolgáltatás elvégzését követően.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-semibold mb-4 text-white">5. Időpont foglalás</h2>
				<p class="text-white/80 leading-relaxed mb-4">
					Időpontfoglalás telefonon vagy emailben lehetséges. A foglalás visszaigazolással válik érvényessé.
				</p>
				<p class="text-white/80 leading-relaxed mb-4">
					Lemondás esetén kérjük, legalább 24 órával korábban jelezzék.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-semibold mb-4 text-white">6. Garancia</h2>
				<p class="text-white/80 leading-relaxed mb-4">
					Szolgáltatásainkra garanciát vállalunk az alábbiak szerint:
				</p>
				<ul class="list-disc list-inside text-white/80 space-y-2 mb-4">
					<li>Polírozás: 3 hónap</li>
					<li>Kerámia bevonat: 1-3 év (típustól függően)</li>
					<li>Belső tisztítás: 1 hónap</li>
				</ul>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-semibold mb-4 text-white">7. Felelősség</h2>
				<p class="text-white/80 leading-relaxed mb-4">
					A szolgáltató kellő szakértelemmel és gondossággal végzi a munkát.
					Meglévő sérülésekért felelősséget nem vállalunk.
				</p>
				<p class="text-white/80 leading-relaxed mb-4">
					Kérjük, a szolgáltatás megkezdése előtt jelezzék a meglévő sérüléseket.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-semibold mb-4 text-white">8. Panaszkezelés</h2>
				<p class="text-white/80 leading-relaxed mb-4">
					Panaszaikat az alábbi elérhetőségeken jelenthetik be:
				</p>
				<ul class="list-disc list-inside text-white/80 space-y-2 mb-4">
					<li>Email: info@carpitgarage.hu</li>
					<li>Telefon: +36 70 333 9809</li>
					<li>Személyesen: 1172 Budapest, Cinkotai út 26.</li>
				</ul>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-semibold mb-4 text-white">9. Záró rendelkezések</h2>
				<p class="text-white/80 leading-relaxed">
					Jelen ÁSZF 2024. december 15. napjától hatályos. A szolgáltató fenntartja a jogot
					az ÁSZF egyoldalú módosítására, melyet a honlapon közzétesz.
				</p>
			</section>

			<div class="text-sm text-white/60 mt-12 pt-8 border-t border-white/20">
				Utolsó frissítés: 2024. december 15.
			</div>
		</div>
	</div>
		</main>
	{/snippet}
</SmoothScrollWrapper>
